# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-09 19:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mag', '0002_maguser_logged_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maguser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='maguser',
            name='logged_in',
        ),
        migrations.RemoveField(
            model_name='maguser',
            name='password',
        ),
        migrations.AddField(
            model_name='maguser',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
