# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-09 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0003_auto_20171209_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='img_url',
        ),
    ]
