# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-09 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0005_auto_20171209_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maguser',
            name='user',
        ),
        migrations.AddField(
            model_name='maguser',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True, verbose_name='Email Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maguser',
            name='first_name',
            field=models.CharField(default=None, max_length=30, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maguser',
            name='last_name',
            field=models.CharField(default=None, max_length=30, verbose_name='Last Name'),
            preserve_default=False,
        ),
    ]
